### ISSUE TITLE
Keepass 2.38 update

### ISSUE THREAD

**Issue by gjf** [heinrich-ulbricht/partial-keepass-database-export#1]
New Keepass version (2.38) requires an update of this addon.

**Comment by heinrich-ulbricht** [comment]
The plugin seems to work fine with 2.38 without any changes.

**Comment by gjf** [comment]
It does not start at all asking about updating plugin for this version of KeePass.

**Comment by heinrich-ulbricht** [comment]
@gjf The version 1.1.1 has been built against KeePass 2.39. Please check if it works.
