### ISSUE TITLE
comparison with KeePassSubsetExport

### ISSUE THREAD

**Issue by bmcdonnell** [heinrich-ulbricht/partial-keepass-database-export#4]
[KeePassSubsetExport](https://github.com/lukeIam/KeePassSubsetExport) is another KeePass plugin that performs the same basic task as this one.

The developer of KeePassSubsetExport [lists some advantages](https://github.com/lukeIam/KeePassSubsetExport#keepasssubsetexport-vs-partial-keepass-database-export) of it over this one. What features or advantages does this plugin have over KeePassSubsetExport, if any? I think it would be a good addition to your README.

**Comment by heinrich-ulbricht** [comment]
@bmcdonnell Good question, the plugin looks good to me. Would've spared me the effort of creating one on my own ;) One thing that is valuable to me that my plugin can do more is clearing the one-time password secret from password entries. Not copying the folder structure _can_ be a feature. And if the other plugin keeps growing simplicity might also speak for my plugin but that is a cheap shot :)

All I can say is go for it if you like it.
